image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - denoland.vscode-deno
    - rust-lang.rust-analyzer
    - Dart-Code.dart-code
    - bierner.markdown-mermaid

tasks:
  - init: dart pub get --directory=./dart/commection
