name: commection
description: A sample command-line application.
version: 0.0.0
repository: https://github.com/narumincho/commection

environment:
  sdk: ^3.0.0

dependencies:
  fast_immutable_collections: ^9.1.2
  meta: ^1.9.1
  narumincho_json: ^0.1.0
  narumincho_util: ^0.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
