name: test

on:
  pull_request

jobs:
  deno-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno editor-build
      - run: deno task example-codegen
      - run: deno check
      - run: deno test
      - run: deno publish --dry-run
