name: test

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  deno-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build step
        run: deno task build-client
      - run: deno check
      - run: deno test
      - run: deno publish --dry-run
